### PR TITLE
Add basic UART xfer

### PR DESCRIPTION
**Pull request by caternuson**
Just the basic AT command xfer. Assume further parsing will be done in command specifics functions to be added later.

```python
Adafruit CircuitPython 5.0.0-rc.0 on 2020-02-26; Adafruit ItsyBitsy nRF52840 Express with nRF52840
>>> import board
>>> from adafruit_rockblock import RockBlock
>>> rb = RockBlock(board.UART())
>>> rb._uart_xfer('+GMI')
'Iridium'
>>> rb._uart_xfer('+GMM')
'IRIDIUM 9600 Family SBD Transceiver'
>>> rb._uart_xfer('hello world')
'ERROR'
>>> rb._uart_xfer('+SBDSX')
'+SBDSX: 0, 1, 0, -1, 0, 0'
>>> 
```

### CODE REVIEW

**Comment by ladyada** [comment]
wanna make this a draft PR while you add more?

**Comment by caternuson** [comment]
```python
Adafruit CircuitPython 5.0.0-rc.0 on 2020-02-26; Adafruit ItsyBitsy nRF52840 Express with nRF52840
>>> import board
>>> from adafruit_rockblock import RockBlock
>>> rb = RockBlock(board.UART())
>>> rb.model
'IRIDIUM 9600 Family SBD Transceiver'
>>> 
```

**Comment by caternuson** [comment]
I think I'd have to re-submit to make it draft? Not seeing a way to change. Or could have a series of PRs that each add some functionality? This is like the very first baby step. More PRs to come later.

And maybe we should create issues as we go also?

**Comment by ladyada** [comment]
well its passin' so im ok mergin for now

**Pull request merged**
